const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'tables-twin-01',
      name: 'Tables Twins 01',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-01.jpg',
      price: 69,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'tables-trio-02',
      name: 'Tables Trio 02',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-02.jpg',
      price: 119,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'tables-twin-03',
      name: 'Tables Twins 03',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-03.jpg',
      price: 109,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'table-glass-04',
      name: 'Table Glass 04',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-04.jpg',
      price: 109,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'table-glass-light-05',
      name: 'Table Glass Light 05',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-05.jpg',
      price: 109,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'table-06',
      name: 'Table 06',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-06.jpg',
      price: 149,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'table-small-07',
      name: 'Table Small 07',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-07.jpg',
      price: 399,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'table-08',
      name: 'Table Small 08',
      category: 'table',
      image: 'src=../../images/furnitures/tables/table-08.jpg',
      price: 449,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-black-01',
      name: 'Sofa Black 01',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-01.jpg',
      price: 799,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-orange-02',
      name: 'Sofa Orange 01',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-02.jpg',
      price: 299,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-grey-03',
      name: 'Sofa Grey 03',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-03.jpg',
      price: 199,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-orange-04',
      name: 'Sofa Orange 04',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-04.jpg',
      price: 339,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-grey-05',
      name: 'Sofa Grey 05',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-05.jpg',
      price: 339,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-grey-06',
      name: 'Sofa Grey 06',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-06.jpg',
      price: 589,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-magnolia-07',
      name: 'Sofa Magnolia 07',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-07.jpg',
      price: 419,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'sofa-dark-yellow-08',
      name: 'Sofa Dark Yellow 08',
      category: 'sofa',
      image: 'src=../../images/furnitures/sofas/sofa-08.jpg',
      price: 419,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },

    {
      id: 'dining-table-brown-01',
      name: 'Dining Table Brown 01',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-01.jpg',
      price: 699,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-modern-02',
      name: 'Dining Table Modern 02',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-02.jpg',
      price: 1299,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-black-03',
      name: 'Dining Table Black 03',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-03.jpg',
      price: 1999,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-white-04',
      name: 'Dining Table White 04',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-04.jpg',
      price: 499,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-wood-05',
      name: 'Dining Table Wood 05',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-05.jpg',
      price: 899,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-beige-06',
      name: 'Dining Table Beige 06',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-06.jpg',
      price: 19.99,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-glass-07',
      name: 'Dining Table Glass 07',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-07.jpg',
      price: 1269.99,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'dining-table-glass-modern-08',
      name: 'Dining Table Glass Modern 08',
      category: 'dining',
      image: 'src=../../images/furnitures/dining/dining-08.jpg',
      price: 1269.99,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'chair-grey-01',
      name: 'Chair Grey 01',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-01.jpg',
      price: 9.99,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'chair-dark-yellow-02',
      name: 'Chair Dark Yellow 02',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-02.jpg',
      price: 299,
      stars: 1,
      userStars: 5,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'chair-green-03',
      name: 'Chair Green 03',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-03.jpg',
      price: 999,
      stars: 4,
      userStars: 1,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'chair-magnolia-04',
      name: 'Chair Magnolia 04',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-04.jpg',
      price: 333,
      stars: 2,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'chair-white-05',
      name: 'Chair White 05',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-05.jpg',
      price: 169,
      stars: 2,
      userStars: 4,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'chair-white-06',
      name: 'Chair White 06',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-06.jpg',
      price: 499,
      stars: 1,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'chair-black-07',
      name: 'Chair Black 07',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-07.jpg',
      price: 999,
      stars: 4,
      userStars: 4,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'chair-green-08',
      name: 'Chair Green 08',
      category: 'chair',
      image: 'src=../../images/furnitures/chairs/chair-08.jpg',
      price: 999,
      stars: 4,
      userStars: 4,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },

    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_001.jpg',
      price: 30,
      stars: 2,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_002.jpg',
      basePrice: '$ 40',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_003.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_004.jpg',
      basePrice: '$ 55',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_005.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_006.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_007.jpg',
      basePrice: '$ 49',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_008.jpg',
      basePrice: '$ 33',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_009.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_010.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_011.jpg',
      basePrice: '$ 45',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_012.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_013.jpg',
      basePrice: '$ 49',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_014.jpg',
      basePrice: '$ 100',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_015.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_016.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_017.jpg',
      basePrice: '$ 44',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_018.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_019.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_020.jpg',
      basePrice: '$ 47',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_021.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_022.jpg',
      basePrice: '$ 40',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_023.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      image: 'src=../../images/furnitures/beds/bed_024.jpg',
      price: 30,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      compare: false,
      favourite: false,
    },
  ],

  reviews: [
    {
      id: 'rev-01',
      clientName: 'Patrick The Irish',
      clientReview:
        'Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.',
      clientPhoto: 'https://i.postimg.cc/G2p6t3tn/patrick-the-irish.jpg',
    },
    {
      id: 'rev-02',
      clientName: 'Merry Christmas',
      clientReview:
        'Nullam euismod aliquet sapien commodo dignissim. Nullam non magna ligula. Aliquam in eros lacinia, vulputate nibh vitae, malesuada erat. Phasellus id lorem sapien. Vestibulum placerat dolor tincidunt libero venenatis, pretium sollicitudin lorem blandit. Vestibulum blandit lorem mauris. Quisque id sem malesuada, tempor nunc non, vehicula risus.',
      clientPhoto: 'https://i.postimg.cc/L6CQvRJX/merry-christmas.jpg',
    },
    {
      id: 'rev-03',
      clientName: 'Happy Easter',
      clientReview:
        'Aliquam eget dui blandit, varius velit eget, sagittis sem. Praesent id dui massa. Fusce pharetra tincidunt eros, vitae pharetra neque. Suspendisse posuere faucibus mauris, vitae consequat tortor fringilla elementum. Maecenas dignissim augue nisi, et posuere lacus facilisis vel. Donec vestibulum elementum mi, id euismod nisl vulputate ac.',
      clientPhoto: 'https://i.postimg.cc/PxfvJGdG/happy-easter.jpg',
    },
  ],
  cart: {
    products: [],
  },
  promotion: [
    {
      id: 'promotion-vertical',
      image: 'src=../../images/promotion/fotel.jpg',
    },
    {
      id: 'promotion-horizontal-1',
      image: 'src=../../images/promotion/sofa.jpg',
    },
    {
      id: 'promotion-horizontal-2',
      image: 'src=../../images/promotion/kredens.jpg',
    },
  ],

  hotDeals: {
    textFirstWord: 'Indoor',
    textSecondWord: ' furniture',
    textSecondline: 'save up to 50% of all furniture',
    pictureLeft: 'src=../../images/hotDeals/armchair.jpg',
    pictureRight: 'src=../../images/hotDeals/living.jpg',
    products: [
      'aenean-ru-bristique-2',
      'aenean-ru-bristique-3',
      'aenean-ru-bristique-4',
    ],
  },

  logo: [
    {
      id: 'logo1',
    },
  ],
};

export default initialState;
